services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: tasks
      POSTGRES_PASSWORD: tasks
      POSTGRES_DB: task-manager-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 2345:5432
volumes:
  pgdata:
