apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: taskmanager
data:
  SERVER_PORT: "9090"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/task-manager-db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: taskmanager
data:
  config.js: |
    window.API_BASE_URL = "http://backend-service:9090/api";
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: taskmanager
data:
  POSTGRES_DB: task-manager-db

