apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: taskmanager
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: tasks
  SPRING_DATASOURCE_PASSWORD: tasks
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: taskmanager
type: Opaque
stringData:
  POSTGRES_USER: tasks
  POSTGRES_PASSWORD: tasks

